create table tb_belonging (position integer, list_id bigint not null, product_id bigint not null, primary key (list_id, product_id));
create table tb_list (id bigserial not null, name varchar(255), primary key (id));
create table tb_product (price float(53), quantity integer, id bigserial not null, img_url varchar(255), name varchar(255), short_description varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKmlkc2p81xm7kiet8pngfy93ru foreign key (product_id) references tb_product;
alter table if exists tb_belonging add constraint FK5rwjd72l3bnb2cyffvh367y4v foreign key (list_id) references tb_list;
INSERT INTO tb_list (name) VALUES ('Frutas');
INSERT INTO tb_list (name) VALUES ('Frutas2');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Laranja', 5, 'www.imglaranja.com', 'Laranja inteira');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Maçã', 7, 'www.imgmaca.com', 'Maçã argentina');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Banana', 10, 'www.imgbanana.com', 'Penca de banana');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Uva', 12, 'www.imguva.com', 'Uva sem semente');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Melancia', 8, 'www.imgmelancia.com', 'Melancia sem caroço');
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (2, 3, 0);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (2, 4, 1);
create table tb_belonging (position integer, list_id bigint not null, product_id bigint not null, primary key (list_id, product_id));
create table tb_list (id bigserial not null, name varchar(255), primary key (id));
create table tb_product (price float(53), quantity integer, id bigserial not null, img_url varchar(255), name varchar(255), short_description varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKmlkc2p81xm7kiet8pngfy93ru foreign key (product_id) references tb_product;
alter table if exists tb_belonging add constraint FK5rwjd72l3bnb2cyffvh367y4v foreign key (list_id) references tb_list;
INSERT INTO tb_list (name) VALUES ('Frutas');
INSERT INTO tb_list (name) VALUES ('Frutas2');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Laranja', 5, 'www.imglaranja.com', 'Laranja inteira');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Maçã', 7, 'www.imgmaca.com', 'Maçã argentina');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Banana', 10, 'www.imgbanana.com', 'Penca de banana');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Uva', 12, 'www.imguva.com', 'Uva sem semente');
INSERT INTO tb_product (name, price, img_Url, short_Description) VALUES ('Melancia', 8, 'www.imgmelancia.com', 'Melancia sem caroço');
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (2, 3, 0);
INSERT INTO tb_belonging (list_id, product_id, position) VALUES (2, 4, 1);
